const pageActionTypes = {
  SET_ACTIVE_PROJECT: 'SET_ACTIVE_PROJECT',
  SET_INVIEW: 'SET_INVIEW',
  SET_VIEW:'SET_VIEW',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  SET_WELCOME_SCREEN: 'SET_WELCOME_SCREEN'
}

export default pageActionTypes